apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: payment-service
  name: payment-service
spec:
  ports:
    - name: "3003"
      port: 3003
      protocol: TCP
      targetPort: 3003
  selector:
    app: payments-ms
  type: NodePort
status:
  loadBalancer: {}
