apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: product-ms
  name: product-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-ms
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: product-ms
    spec:
      containers:
        - image: us-east1-docker.pkg.dev/annular-heading-423723-a4/tienda/product-ms
          name: product-ms
          env:
            - name: DATABASE_URL
              value: "file:./dev.db"
            - name: NATS_SERVERS
              value: "nats://nats"
          resources:
            requests:
              memory: "64Mi"
              cpu: "200m"
            limits:
              memory: "128Mi"
              cpu: "400m"
status: {}
